namespace: deps-lead-svc

imagePullSecrets:
  - name: harbor-registry-secret

frontend:
  replicaCount: 2
  image:
    repository: harbor.javajon-gke.duckdns.org/deps/outreach-ui
    tag: "v3"
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 80
    nodePort: 30080

campaign:
  replicaCount: 2
  image:
    repository: harbor.javajon-gke.duckdns.org/library/campaign-svc
    tag: "v2"
    pullPolicy: Always

lead:
  replicaCount: 2
  image:
    repository: harbor.javajon-gke.duckdns.org/deps/lead-svc
    tag: "v1"
    pullPolicy: IfNotPresent

auth:
  replicaCount: 2
  image:
    repository: harbor.javajon-gke.duckdns.org/deps/auth-svc
    tag: "v2"
    pullPolicy: Always
  service:
    type: NodePort
    port: 8083

ai:
  replicaCount: 1
  image:
    repository: harbor.javajon-gke.duckdns.org/library/ai-svc
    tag: "v2"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8090

rabbitmq:
  replicaCount: 1
  image:
    repository: rabbitmq
    tag: "3.12-management-alpine"

ingress:
  enabled: true
  host: outreach.javajon-gke.duckdns.org


