apiVersion: v1
kind: Service
metadata:
  name: ai-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ai-svc
  ports:
    - protocol: TCP
      port: {{ .Values.ai.service.port }}
      targetPort: 8090
  type: {{ .Values.ai.service.type }}


