apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.auth.replicaCount }}
  selector:
    matchLabels:
      app: auth-svc
  template:
    metadata:
      labels:
        app: auth-svc
    spec:
      imagePullSecrets:
{{- range .Values.imagePullSecrets }}
      - name: {{ .name | default .name | default . }}
{{- end }}
      containers:
        - name: auth-svc
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: outreach-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: outreach-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: outreach-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: outreach-secrets
                  key: JWT_SECRET
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: outreach-secrets
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: outreach-secrets
                  key: MAIL_PASSWORD
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: outreach-config
                  key: AUTH_SERVICE_PORT


