apiVersion: v1
kind: ConfigMap
metadata:
  name: outreach-config
  namespace: {{ .Values.namespace }}
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "outreachdb"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: "/"
  AI_REQUEST_QUEUE: "ai.email.generation.requests"
  AI_RESPONSE_QUEUE: "ai.email.generation.responses"
  AI_ERROR_QUEUE: "ai.email.generation.errors"
  AI_SERVICE_URL: "http://ai-svc:8090"
  LEAD_SERVICE_URL: "http://lead-svc:8081"
  AUTH_SERVICE_PORT: "8083"
  CAMPAIGN_SERVICE_PORT: "8081"
  LEAD_SERVICE_PORT: "8081"
  AI_SERVICE_PORT: "8090"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/outreachdb"
  OPENAI_MODEL: "gpt-4o-mini"
  OPENAI_BASE_URL: ""
  GEMINI_API_URL: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
  REACT_APP_AUTH_URL: "http://localhost:8083/api/v1/auth"
  REACT_APP_API_URL: "http://localhost:8081/api/v1"
  PUBLIC_API_ENABLED: "false"
  PUBLIC_API_BASE_URL: ""
  PUBLIC_API_TIMEOUT: "10000"


