apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: outreach-ui
  template:
    metadata:
      labels:
        app: outreach-ui
    spec:
      imagePullSecrets:
{{- range .Values.imagePullSecrets }}
      - name: {{ .name | default .name | default . }}
{{- end }}
      containers:
        - name: outreach-ui
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_AUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: outreach-config
                  key: REACT_APP_AUTH_URL
            - name: REACT_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: outreach-config
                  key: REACT_APP_API_URL


