{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: outreach-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE, PATCH"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,X-User-Email"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api/v1/campaigns
            pathType: Prefix
            backend:
              service:
                name: campaign-svc
                port:
                  number: 8081
          - path: /api/v1/auth
            pathType: Prefix
            backend:
              service:
                name: auth-svc
                port:
                  number: 8083
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: lead-svc
                port:
                  number: 8081
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80
    - http:
        paths:
          - path: /api/v1/campaigns
            pathType: Prefix
            backend:
              service:
                name: campaign-svc
                port:
                  number: 8081
          - path: /api/v1/auth
            pathType: Prefix
            backend:
              service:
                name: auth-svc
                port:
                  number: 8083
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: lead-svc
                port:
                  number: 8081
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80
{{- end }}


