apiVersion: apps/v1
kind: Deployment
metadata:
  name: lead-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.lead.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: LeadsApp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: LeadsApp
    spec:
      imagePullSecrets:
{{- range .Values.imagePullSecrets }}
      - name: {{ .name | default .name | default . }}
{{- end }}
      containers:
        - name: lead-svc
          image: "{{ .Values.lead.image.repository }}:{{ .Values.lead.image.tag }}"
          imagePullPolicy: {{ .Values.lead.image.pullPolicy }}
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: outreach-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: outreach-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: outreach-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: outreach-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: outreach-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: outreach-secrets
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: outreach-secrets
                  key: RABBITMQ_PASSWORD
            - name: AI_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: outreach-config
                  key: AI_SERVICE_URL
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: outreach-config
                  key: LEAD_SERVICE_PORT


