server.port=8081
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger

gemini.api.key=AIzaSyAWkG54KoJ5rcIzxexy0LMHhT2ur6X1hoE
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent